In [1]:
import re
import sklearn
import gensim
from gensim.models import Word2Vec
import numpy as np

def preprocess_company_names(company_names):
    processed_names = []
    for name in company_names:
        # Remove punctuation
        name = re.sub(r'[^\w\s]', '', name)
        # Convert to lowercase
        name = name.lower()
        # Expand common abbreviations
        name = re.sub(r'\bltd\b', 'limited', name)
        name = re.sub(r'\bpvt\b', 'private', name)
        name = re.sub(r'\bcorp\b', 'corporation', name)
        name = re.sub(r'\binc\b', 'incorporation', name)

        name = re.sub(r'\blimited\b', '', name)
        name = re.sub(r'\bprivate\b', '', name)
        name = re.sub(r'\bcorporation\b', '', name)
        name = re.sub(r'\bincorporation\b', '', name)

        # Add more expansions as needed
        
        processed_names.append(name)
    
    return processed_names


company_names = [
    'Apple Inc.', 'Apple', 'AAPL Inc.', 'Apple Corp', 'Apple Computers', 'Appl Inc.', 'Apple Incorporation', 'Applle', 'Aple Inc',
    'Microsoft Corporation', 'Microsoft Corp.', 'MSFT Inc.', 'MS Corp', 'Microsoft', 'Microsft', 'Microsof Corporation', 'Microsfot',
    'Amazon.com, Inc.', 'Amazon', 'AMZN', 'Amazon Corp', 'Amazon Services', 'Amazn', 'Amzon', 'Amazom Inc', 'Amazom',
    'Alphabet Inc.', 'Alphabet', 'Google LLC', 'Google Inc.', 'Google', 'Alphabt', 'Alphabe Inc.', 'Googel', 'Goole Inc',
    'Facebook, Inc.', 'Facebook', 'FB Inc.', 'Meta Platforms', 'Meta', 'Facebok', 'Facbook Inc.', 'Metaa', 'Mta Platforms',
    'Tesla, Inc.', 'Tesla Motors', 'Tesla', 'TSLA', 'Tesla Energy', 'Tesl Inc', 'Telsa', 'Tesla Incorporation', 'Tesl',
    'Berkshire Hathaway Inc.', 'Berkshire Hathaway', 'Berkshire Inc.', 'BRK.A', 'BRK.B', 'Berkshire Hatway', 'Berkshire Hthaway Inc.', 'Berkshre', 'Berkshire Hathway',
    'Alibaba Group Holding Limited', 'Alibaba', 'Alibaba Group', 'BABA', 'Ali Baba', 'Alibba', 'Alibab Group', 'AliBaba Holding', 'Alibab',
    'Johnson & Johnson', 'Johnson and Johnson', 'J&J', 'JNJ', 'Johnson', 'Johnsn & Johnson', 'Johnson & Johson', 'J & J', 'Johnson Johnson',
    'JPMorgan Chase & Co.', 'JP Morgan Chase', 'JPM Chase', 'JPMC', 'J.P. Morgan', 'JPMorgan', 'JP Morgan', 'JP MorganChase', 'JPMogan',
    'Visa Inc.', 'Visa', 'V', 'Visa Corporation', 'Visa Corp', 'Vsa', 'Visa Incorporation', 'Visa Inc', 'VisaIncorporation',
    'Samsung Electronics', 'Samsung', 'Samsung Corp.', 'Samsung Ltd.', 'Samsung Co.', 'Samsng', 'Samusng', 'Sammsung', 'Samsong',
    'Nestlé S.A.', 'Nestle', 'Nestle Inc.', 'Nestle SA', 'Nestle Ltd.', 'Nestl', 'Nestl Inc', 'Nestl S.A', 'Nestlee',
    'Procter & Gamble', 'Procter and Gamble', 'P&G', 'Proctor & Gamble', 'Procter & Gambl', 'Proctre & Gamble', 'P and G', 'P&G Inc.', 'Procter',
    'Toyota Motor Corporation', 'Toyota', 'Toyota Motors', 'TM', 'Toyota Corp', 'Toyta', 'Toyot', 'Toyota Motor Corp.', 'Toyta Motor',
    'Walt Disney Company', 'Disney']
print(len(company_names))



# Preprocess company names
processed_company_names = preprocess_company_names(company_names)

print(processed_company_names)


136
['apple ', 'apple', 'aapl ', 'apple ', 'apple computers', 'appl ', 'apple ', 'applle', 'aple ', 'microsoft ', 'microsoft ', 'msft ', 'ms ', 'microsoft', 'microsft', 'microsof ', 'microsfot', 'amazoncom ', 'amazon', 'amzn', 'amazon ', 'amazon services', 'amazn', 'amzon', 'amazom ', 'amazom', 'alphabet ', 'alphabet', 'google llc', 'google ', 'google', 'alphabt', 'alphabe ', 'googel', 'goole ', 'facebook ', 'facebook', 'fb ', 'meta platforms', 'meta', 'facebok', 'facbook ', 'metaa', 'mta platforms', 'tesla ', 'tesla motors', 'tesla', 'tsla', 'tesla energy', 'tesl ', 'telsa', 'tesla ', 'tesl', 'berkshire hathaway ', 'berkshire hathaway', 'berkshire ', 'brka', 'brkb', 'berkshire hatway', 'berkshire hthaway ', 'berkshre', 'berkshire hathway', 'alibaba group holding ', 'alibaba', 'alibaba group', 'baba', 'ali baba', 'alibba', 'alibab group', 'alibaba holding', 'alibab', 'johnson  johnson', 'johnson and johnson', 'jj', 'jnj', 'johnson', 'johnsn  johnson', 'johnson  johson', 'j  j', 'johnso

In [2]:
from fuzzywuzzy import fuzz
import numpy as np

# Number of companies
n = len(company_names)

# Initialize the similarity matrix
similarity_matrix = np.zeros((n, n))

# Compute similarity scores
for i in range(n):
    for j in range(n):
        if i != j:
            similarity_matrix[i, j] = fuzz.ratio(processed_company_names[i], processed_company_names[j])
        else:
            similarity_matrix[i, j] = 100  # Maximum similarity with itself

# Display the similarity matrix
print(similarity_matrix)


c:\Users\shubh\AppData\Local\Programs\Python\Python310\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


[[100.  91.  73. ...  24.  16.  17.]
 [ 91. 100.  60. ...  12.  17.  18.]
 [ 73.  60. 100. ...  25.  17.   0.]
 ...
 [ 24.  12.  25. ... 100.  20.  12.]
 [ 24.  25.  25. ...  20. 100.  48.]
 [ 17.  18.   0. ...  12.  48. 100.]]


In [3]:
""" from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(processed_company_names)

print(X)


X_dense = X.toarray()


print("Feature Matrix (TF-IDF representation):\n", X_dense)

 """

  (0, 17)	1.0
  (1, 17)	1.0
  (2, 0)	1.0
  (3, 17)	1.0
  (4, 17)	0.6198083338665895
  (4, 27)	0.7847532282632054
  (5, 16)	1.0
  (6, 17)	1.0
  (7, 18)	1.0
  (8, 15)	1.0
  (9, 62)	1.0
  (10, 62)	1.0
  (11, 68)	1.0
  (12, 67)	1.0
  (13, 62)	1.0
  (14, 60)	1.0
  (15, 61)	1.0
  (16, 59)	1.0
  (17, 11)	1.0
  (18, 10)	1.0
  (19, 12)	1.0
  (20, 10)	1.0
  (21, 10)	0.655241142049617
  (21, 85)	0.755419781158472
  (22, 8)	1.0
  :	:
  (119, 77)	0.7714888204957104
  (120, 76)	0.6362428780349038
  (120, 35)	0.7714888204957104
  (121, 36)	0.6362428780349038
  (121, 78)	0.7714888204957104
  (122, 14)	1.0
  (123, 74)	1.0
  (124, 76)	1.0
  (125, 91)	0.6732697882708322
  (125, 65)	0.7393969111389017
  (126, 91)	1.0
  (127, 66)	0.7595974874024402
  (127, 91)	0.6503934633219339
  (128, 89)	1.0
  (129, 91)	1.0
  (130, 92)	1.0
  (131, 90)	1.0
  (132, 91)	0.6732697882708322
  (132, 65)	0.7393969111389017
  (133, 65)	0.6850383514650138
  (133, 92)	0.7285070054722167
  (134, 97)	0.5922584684249063
  (134, 28)	

In [16]:
from sklearn.cluster import DBSCAN
from sklearn.metrics import pairwise_distances

# Compute the distance matrix
distance_matrix = 100 - similarity_matrix

from sklearn.metrics.pairwise import cosine_distances

#word_cosine = cosine_distances(distance_matrix)

dbscan = DBSCAN(metric='precomputed', eps=10, min_samples=2)
labels = dbscan.fit_predict(distance_matrix)

print(labels)

clusters = {}
for idx, label in enumerate(labels):
    if label not in clusters:
        clusters[label] = []
    clusters[label].append(company_names[idx])

print("\nClusters:")
for cluster_id, members in clusters.items():
    print(f"Cluster {cluster_id}: {members}")

[ 0  0 -1  0 -1  0  0  0  0  1  1 -1 -1  1  1  1  1 -1  2 -1  2 -1  2  2
  3  3  4  4 -1  5  5  4  4 -1  5  6  6 -1  7 -1  6  6 -1  7  8 -1  8 -1
 -1  8 -1  8 -1  9  9 -1 -1 -1  9  9 -1  9 -1 10 11 -1 10 10 11 -1 10 12
 12 -1 -1 -1 12 12 -1 12 -1 13 -1 -1 14 14 14 13 14 15 -1 -1 15 15 -1 15
 15 -1 -1 16 16 16 -1 16 16 16 16 17 18 18 17 18 18 18 17 18 19 19 -1 19
 19 19 -1 -1 -1 20 21 20 -1 21 21 21 20 20 -1 -1]

Clusters:
Cluster 0: ['Apple Inc.', 'Apple', 'Apple Corp', 'Appl Inc.', 'Apple Incorporation', 'Applle', 'Aple Inc']
Cluster -1: ['AAPL Inc.', 'Apple Computers', 'MSFT Inc.', 'MS Corp', 'Amazon.com, Inc.', 'AMZN', 'Amazon Services', 'Google LLC', 'Googel', 'FB Inc.', 'Meta', 'Metaa', 'Tesla Motors', 'TSLA', 'Tesla Energy', 'Telsa', 'Tesl', 'Berkshire Inc.', 'BRK.A', 'BRK.B', 'Berkshre', 'Alibaba Group Holding Limited', 'BABA', 'AliBaba Holding', 'J&J', 'JNJ', 'Johnson', 'J & J', 'JPMorgan Chase & Co.', 'JPM Chase', 'JPMC', 'Visa', 'V', 'Vsa', 'VisaIncorporation', 'Samsung Elect

In [17]:
for cluster_id, members in clusters.items():
    print(f"Cluster {cluster_id}:" , len(members))

Cluster 0: 7
Cluster -1: 44
Cluster 1: 6
Cluster 2: 4
Cluster 3: 2
Cluster 4: 4
Cluster 5: 3
Cluster 6: 4
Cluster 7: 2
Cluster 8: 4
Cluster 9: 5
Cluster 10: 4
Cluster 11: 2
Cluster 12: 5
Cluster 13: 2
Cluster 14: 4
Cluster 15: 5
Cluster 16: 7
Cluster 17: 3
Cluster 18: 6
Cluster 19: 5
Cluster 20: 4
Cluster 21: 4


In [18]:

from sklearn.metrics import pairwise_distances

distance_matrix = 100 - similarity_matrix

preferences = np.linspace(np.min(similarity_matrix), np.max(similarity_matrix), 10)


affinity_propagation = AffinityPropagation(random_state=0, affinity="euclidean", verbose=2, max_iter=500)
labels = affinity_propagation.fit_predict(distance_matrix)

print(labels)

clusters = {}
for idx, label in enumerate(labels):
    if label not in clusters:
        clusters[label] = []
    clusters[label].append(company_names[idx])

print("\nClusters:")
for cluster_id, members in clusters.items():
    print(f"Cluster {cluster_id}: {members}")

Converged after 60 iterations.
[ 0  0  0  0 20  0  0  0  0  1  1  1 14  1  1  1  1  2  2  2  2  2  2  2
  2  2  3  3  4  4  4  3  3  4  4  5  5  5  6  6  5  5  6 19  7 19  7  7
  7  7  7  7  7  9  9  9  8  8  9  9  9  9 20 10 10 10 10 10 10 10 10 12
 12 11 11 12 12 12 11 12 13 13 13 18 13 13 13 13 13 14 14 11 14 14 14 14
 14 20 15 15 15 15 15 15 15 15 15 16 16 16 16 16 16 16 16 16 17 17 18 17
 17 17 20 18 17 19 19 19  6 19 19 19 19 19 20 20]

Clusters:
Cluster 0: ['Apple Inc.', 'Apple', 'AAPL Inc.', 'Apple Corp', 'Appl Inc.', 'Apple Incorporation', 'Applle', 'Aple Inc']
Cluster 20: ['Apple Computers', 'Alibaba Group Holding Limited', 'VisaIncorporation', 'P and G', 'Walt Disney Company', 'Disney']
Cluster 1: ['Microsoft Corporation', 'Microsoft Corp.', 'MSFT Inc.', 'Microsoft', 'Microsft', 'Microsof Corporation', 'Microsfot']
Cluster 14: ['MS Corp', 'Visa Inc.', 'Visa', 'Visa Corporation', 'Visa Corp', 'Vsa', 'Visa Incorporation', 'Visa Inc']
Cluster 2: ['Amazon.com, Inc.', 'Amazon', '

In [19]:
for cluster_id, members in clusters.items():
    print(f"Cluster {cluster_id}:" , len(members))

Cluster 0: 8
Cluster 20: 6
Cluster 1: 7
Cluster 14: 8
Cluster 2: 9
Cluster 3: 4
Cluster 4: 5
Cluster 5: 5
Cluster 6: 4
Cluster 19: 10
Cluster 7: 8
Cluster 9: 7
Cluster 8: 2
Cluster 10: 8
Cluster 12: 6
Cluster 11: 4
Cluster 13: 8
Cluster 18: 3
Cluster 15: 9
Cluster 16: 9
Cluster 17: 6
